name: Pull Request Checks

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .Net 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Install Dependencies
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build -warnaserror --no-restore

      - name: Install .Net Tools
        run: dotnet tool restore

      - name: Run Csharpier Check
        run: dotnet csharpier check .

      - name: Run Unit / Integration Tests
        run: dotnet test
